services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
    - .env
    command: ["node", "dist/src/main.js"]
    expose:
      - 3000
    ports:
      - 4000:3000
    tty: true