services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    expose:
      - 3000
    ports:
      - 3000:3000
    tty: true